name-template: "$(date +'%Y-%m-%d %H:%M:%S')"
tag-template: "release-$(date +'%Y-%m-%d %H:%M:%S')"
categories:
  - title: '✅ Tested on stg'
    label: 'tested on stg'
  - title: '🔕 No stg test needed'
    label: 'no stg test needed'
change-template: '* $TITLE ($URL) @$AUTHOR'
template: |
  ## Untested changes

  $CHANGES
