name: 'Release Drafter'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [labeled]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Create tag name
        run: |
          TAG_NAME="$(node -e "console.log(new Date().toLocaleString('ja-JP').replace(/[\s\:\/]/g, ''))")"
          echo "tag_name=$TAG_NAME" >> "$GITHUB_ENV"
      - uses: release-drafter/release-drafter@v6
        with:
          name: ${{ env.tag_name }}
          tag: release-${{ env.tag_name }}
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
