name: 'Release Drafter'

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    types: [labeled]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - run: |
          TAG_NAME=$(node -e "console.log(new Date().toLocaleString('ja-JP').replace(/[\s\:\/]/g, ''))")
          echo "tag_name=$TAG_NAME" >> $GITHUB_ENV
          echo $TAG_NAME
      - uses: release-drafter/release-drafter@v6
        with:
          name: ${{ env.tag_name }}
          tag: release-${{ env.tag_name }}
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
